testing

diff --git a/.github/workflows/postman-cicd.yml b/.github/workflows/postman-cicd.yml
--- a/.github/workflows/postman-cicd.yml
+++ b/.github/workflows/postman-cicd.yml
@@ -14,17 +14,16 @@ jobs:
         run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
       - name: Run API tests
         run: |
-          postman collection run "18042228-96a52346-19a3-4b5b-86a4-a285015754f4" -e "18042228-5943a5be-8a17-4140-b6bd-c8b60ae2b80a"
-      - name: Save test Results
-        run: |
-          postman collection run "18042228-96a52346-19a3-4b5b-86a4-a285015754f4" -e "18042228-5943a5be-8a17-4140-b6bd-c8b60ae2b80a" --reporters=json --reporter-json-export=postman-report.json
-      - name: Check for failed status codes
-        run: |
-          echo "Checking API response codes..."
-          cat postman-report.json | jq ".run.executions[].response.code"
-          if cat postman-report.json | jq -e '.run.executions[].response.code | tostring | select(. | test("^[^2|3]"))' > /dev/null; then
-            echo "❌ API test failed: Found response codes outside 2xx or 3xx range."
-            exit 1
-          else
-            echo "✅ All API tests passed successfully."
-          fi  
+          postman collection run "20703100-34b9c6e9-91e0-4400-b7fb-186bd2cc7940" -e "20703100-10eb1b91-084c-4755-a36a-5f1fcd026057"      # - name: Save test Results
+      #   run: |
+      #     postman collection run "18042228-96a52346-19a3-4b5b-86a4-a285015754f4" -e "18042228-5943a5be-8a17-4140-b6bd-c8b60ae2b80a" --reporters=json --reporter-json-export=postman-report.json
+      # - name: Check for failed status codes
+      #   run: |
+      #     echo "Checking API response codes..."
+      #     cat postman-report.json | jq ".run.executions[].response.code"
+      #     if cat postman-report.json | jq -e '.run.executions[].response.code | tostring | select(. | test("^[^2|3]"))' > /dev/null; then
+      #       echo "❌ API test failed: Found response codes outside 2xx or 3xx range."
+      #       exit 1
+      #     else
+      #       echo "✅ All API tests passed successfully."
+      #     fi  
