testing

diff --git a/.github/workflows/postman-cicd-graph.yml b/.github/workflows/postman-cicd-graph.yml
--- a/.github/workflows/postman-cicd-graph.yml
+++ b/.github/workflows/postman-cicd-graph.yml
@@ -15,16 +15,16 @@ jobs:
       - name: Run API tests
         run: |
           postman collection run 42342525-bd1340df-c6d8-4b06-9527-b10a91ef4962 -e 42342525-f621a73e-f222-48a5-a64b-db085f039461
-      - name: Save test Results
-        run: |
-         postman collection run 42342525-bd1340df-c6d8-4b06-9527-b10a91ef4962 -e 42342525-f621a73e-f222-48a5-a64b-db085f039461 --reporters=json --reporter-json-export=postman-report.json
-      - name: Check for failed status codes
-        run: |
-          echo "Checking API response codes..."
-          cat postman-report.json | jq ".run.executions[].response.code"
-          if cat postman-report.json | jq -e '.run.executions[].response.code | tostring | select(. | test("^[^2|3]"))' > /dev/null; then
-            echo "❌ API test failed: Found response codes outside 2xx or 3xx range."
-            exit 1
-          else
-            echo "✅ All API tests passed successfully."
-          fi  
+      # - name: Save test Results
+      #   run: |
+      #    postman collection run 42342525-bd1340df-c6d8-4b06-9527-b10a91ef4962 -e 42342525-f621a73e-f222-48a5-a64b-db085f039461 --reporters=json --reporter-json-export=postman-report.json
+      # - name: Check for failed status codes
+      #   run: |
+      #     echo "Checking API response codes..."
+      #     cat postman-report.json | jq ".run.executions[].response.code"
+      #     if cat postman-report.json | jq -e '.run.executions[].response.code | tostring | select(. | test("^[^2|3]"))' > /dev/null; then
+      #       echo "❌ API test failed: Found response codes outside 2xx or 3xx range."
+      #       exit 1
+      #     else
+      #       echo "✅ All API tests passed successfully."
+      #     fi  
